name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hinorpio/comp7940_api:latest
           
      - name: Deploy to AWS Lightsail Instance 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_INSTANCE_1_IP }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: 22
          script: |
            docker pull hinorpio/comp7940_api:latest
            docker stop api-server || true
            docker rm api-server || true
            docker run -d --name api-server -p 80:5000 \
               -e DB_ENDPOINT=${{ secrets.DB_ENDPOINT }} \
               -e DB_NAME=${{ secrets.DB_NAME }} \
               -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
               -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
               hinorpio/comp7940_api:latest

      - name: Deploy to AWS Lightsail Instance 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_INSTANCE_2_IP }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            docker pull hinorpio/comp7940_api:latest
            docker stop api-server || true
            docker rm api-server || true
            docker run -d --name api-server -p 80:5000 \
               -e DB_ENDPOINT=${{ secrets.DB_ENDPOINT }} \
               -e DB_NAME=${{ secrets.DB_NAME }} \
               -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
               -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
               hinorpio/comp7940_api:latest
